US_LOCATIONS = [
    "US-AL",
    "US-AK",
    "US-AZ",
    "US-AR",
    "US-CA",
    "US-CO",
    "US-CT",
    "US-DE",
    "US-DC",
    "US-FL",
    "US-GA",
    "US-HI",
    "US-ID",
    "US-IL",
    "US-IN",
    "US-IA",
    "US-KS",
    "US-KY",
    "US-LA",
    "US-ME",
    "US-MD",
    "US-MA",
    "US-MI",
    "US-MN",
    "US-MS",
    "US-MO",
    "US-MT",
    "US-NE",
    "US-NV",
    "US-NH",
    "US-NJ",
    "US-NM",
    "US-NY",
    "US-NC",
    "US-ND",
    "US-OH",
    "US-OK",
    "US-OR",
    "US-PA",
    "US-RI",
    "US-SC",
    "US-SD",
    "US-TN",
    "US-TX",
    "US-UT",
    "US-VT",
    "US-VA",
    "US-WA",
    "US-WV",
    "US-WI",
    "US-WY",
]

US_SUMMITS = {
    "W0C": ['US-CO'],
    "W0D": ['US-ND', 'US-SD'],
    "W0I": ['US-IA'],
    "W0M": ['US-MO'],
    "W0N": ['US-NE'],
    "W1": ['US-CT', 'US-ME', 'US-MA', 'US-NH', 'US-RI', 'US-VT'],
    "W2": ['US-NY', 'US-NJ'],
    "W3": ['US-PA', 'US-MD', 'US-DE'],
    "W4A": ['US-AL'],
    "W4C": ['US-NC', 'US-SC'],
    "W4G": ['US-GA'],
    "W4K": ['US-KY'],
    "W4T": ['US-TN'],
    "W4V": ['US-VA'],
    "W5A": ['US-AR'],
    "W5M": ['US-MS'],
    "W5N": ['US-NM'],
    "W5O": ['US-OK'],
    "W5T": ['US-TX'],
    "W6": ['US-CA'],
    "W7A": ['US-AZ'],
    "W7I": ['US-ID'],
    "W7M": ['US-MT'],
    "W7N": ['US-NV'],
    "W7O": ['US-OR'],
    "W7U": ['US-UT'],
    "W7W": ['US-WA'],
    "W7Y": ['US-WY'],
    "W8M": ['US-MI'],
    "W8O": ['US-OH'],
    "W8V": ['US-WV'],
    "W9": ['US-IN', 'US-IL'],
}
